
CREATE DATABASE Khronos charset=utf8 ;

DROP TABLE IF EXISTS User;
CREATE TABLE User
(idUser INTEGER PRIMARY KEY AUTO_INCREMENT,
pseudo VARCHAR(50) NOT NULL, 
mail VARCHAR(50) NOT NULL,
offre INTEGER,
pwd VARCHAR(100) NOT NULL,
etat ENUM('connecte', 'deconnecte'), 
admin INTEGER 
);

DROP TABLE IF EXISTS siteUser;
CREATE TABLE siteUser
(idSite INTEGER PRIMARY KEY AUTO_INCREMENT,
idUser INTEGER NOT NULL,
tmp INTEGER NOT NULL,
nomSite VARCHAR(45) NOT NULL);

DROP TABLE IF EXISTS fichier;
CREATE TABLE fichier
(idFichier INTEGER PRIMARY KEY AUTO_INCREMENT,
idUser INTEGER NOT NULL,
tmp INTEGER NOT NULL);

DROP TABLE IF EXISTS mail;
CREATE TABLE mail
(idmail INTEGER PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(100) NOT NULL);
